### ISSUE TITLE
[1.15.2] server crash

### ISSUE THREAD

**Issue by Quu1337** [blay09/FarmingForBlockheads#92] opened 2020-05-04 04:30 UTC
Got couple server crashes after scheduled restart, all ~3 looking same.

`java.lang.ClassCastException: java.lang.Double cannot be cast to java.lang.Float`

https://pastebin.com/6ire0nsY

**Comment by BlayTheNinth** [comment] 2020-05-04 04:54
Duplicate of #90, update to v6.1.2

**Closed as completed by BlayTheNinth** 2020-05-04 04:54 UTC
Labels: Bug, Duplicate, Crash
