### ISSUE TITLE
JEI for the Market is not visible if on a Server.

### ISSUE THREAD

**Issue by Gbergz** [blay09/FarmingForBlockheads#158] opened 2022-06-06 16:10 UTC
### Minecraft Version

1.18.x

### Mod Loader

Forge

### Mod Loader Version

40.1.47

### Mod Version

10.0.1 | https://www.curseforge.com/minecraft/mc-mods/farming-for-blockheads/files/3710119

### Describe the Issue

The JEI tab for the Market is not visible if you're on a Server. (It does work fine in Singleplayer.)

The tab in question:
![image](https://user-images.githubusercontent.com/26634554/172200533-6bae9518-e93d-40f5-9f41-4ec5efd249a3.png)

### Do you use any performance-enhancing mods (e.g. OptiFine)?

No.

**Comment by BlayTheNinth** [comment] 2022-06-12 19:33
Duplicate of #126

**Closed as not planned by BlayTheNinth** 2022-06-12 19:33 UTC
Labels: Bug, Duplicate
