### ISSUE TITLE
Crash at startup

### ISSUE THREAD

**Issue by agentwolf88** [blay09/FarmingForBlockheads#149] opened 2022-03-22 14:48 UTC
### Minecraft Version

1.18.x

### Mod Loader

Forge

### Mod Loader Version

40.0.22

### Mod Version

farmingforblockheads-forge-1.18.2-10.0.0.jar

### Describe the Issue

Start the game and it crashs.

[crash-2022-03-22_15.42.57-fml.txt](https://github.com/ModdingForBlockheads/FarmingForBlockheads/files/8325315/crash-2022-03-22_15.42.57-fml.txt)

### Logs

https://github.com/ModdingForBlockheads/FarmingForBlockheads/files/8325315/crash-2022-03-22_15.42.57-fml.txt

### Do you use any performance-enhancing mods (e.g. OptiFine)?

Optifine, Starlight

**Comment by BlayTheNinth** [comment] 2022-03-23 23:00
Duplicate of #146

**Closed as completed by BlayTheNinth** 2022-03-23 23:00 UTC
Labels: Bug, Duplicate, Crash
