### ISSUE TITLE
Crash with Oh Biomes youll go.

### ISSUE THREAD

**Issue by agentwolf88** [blay09/FarmingForBlockheads#150] opened 2022-03-22 18:12 UTC
### Minecraft Version

1.18.x

### Mod Loader

Forge

### Mod Loader Version

40.0.22

### Mod Version

farmingforblockheads-forge-1.18.2-10.0.0.jar

### Describe the Issue

Crash when i try to use with Oh the biomes youll go.
[crash-2022-03-22_19.07.36-client.txt](https://github.com/ModdingForBlockheads/FarmingForBlockheads/files/8326868/crash-2022-03-22_19.07.36-client.txt)

### Logs

https://github.com/ModdingForBlockheads/FarmingForBlockheads/files/8326868/crash-2022-03-22_19.07.36-client.txt

### Do you use any performance-enhancing mods (e.g. OptiFine)?

no

**Comment by BlayTheNinth** [comment] 2022-03-23 23:00
Duplicate of #149

**Closed as completed by BlayTheNinth** 2022-03-23 23:00 UTC
Labels: Bug, Duplicate, Crash
